apiVersion: v1
kind: Service
metadata:
  name: my-cloud-config-server-svc
spec:
  ports:
  - name: aplication-port
    port: 8080
    targetPort: 8080
  selector:
    app: my-cloud-config-server
  type: LoadBalancer
