apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleforum-board-consumer-deploy
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: simpleforum-board-consumer
        image: yellowsunn/simpleforum-board-consumer
        ports:
        - containerPort: 8080
