apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simpleforum-zookeeper-sts
spec:
  replicas: 1
  serviceName: simpleforum-zookeeper-svc
  template:
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: simpleforum-zookeeper
        image: confluentinc/cp-zookeeper:7.0.9
        ports:
        - protocol: TCP
          containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        livenessProbe:
          exec:
            command: ['/bin/bash', '-c', 'echo "ruok" | nc -w 2 localhost 2181 | grep imok']
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1
        readinessProbe:
          exec:
            command: ['/bin/bash', '-c', 'echo "ruok" | nc -w 2 localhost 2181 | grep imok']
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1
