apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-

images:
- name: yellowsunn/simpleforum-notification-service
  newTag: SNAPSHOT-20230610003019
resources:
- ../../base
