apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-msa-user-app-deploy

spec:
  template:
    spec:
      containers:
      - name: login-msa-user-app
        resources:
          requests:
            cpu: 256m
            memory: 128Mi
          limits:
            cpu: 512m
            memory: 256Mi
