apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
patchesStrategicMerge:
- ./deployment-patches.yaml
- ./hpa-patches.yaml

images:
- name: yellowsunn/login-msa-user-app
  newTag: SNAPSHOT-20230310144201
resources:
- ../../base
