apiVersion: v1
kind: Service
metadata:
  name: login-msa-vuejs-app-svc
spec:
  ports:
  - name: aplication-port
    port: 80
    targetPort: 80
  selector:
    app: login-msa-vuejs-app
  type: LoadBalancer
  loadBalancerIP: 192.168.29.21