apiVersion: v1
kind: Service
metadata:
  name: simpleforum-image-service-svc
spec:
  ports:
  - name: aplication-port
    port: 8080
    targetPort: 8080
  selector:
    app: simpleforum-image-service
  type: ClusterIP