apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: login-msa-user-app-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: login-msa-user-app-deploy
  targetCPUUtilizationPercentage: 50