apiVersion: v1
kind: Service
metadata:
  name: login-msa-user-app-svc
spec:
  ports:
  - name: aplication-port
    port: 8080
    targetPort: 8080
  selector:
    app: login-msa-user-app
  type: LoadBalancer
