apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simpleforum-notification-service-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simpleforum-notification-service-deploy
  targetCPUUtilizationPercentage: 50
