apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-msa-api-gateway-app-deploy
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: login-msa-api-gateway-app
        image: yellowsunn/login-msa-api-gateway-app
        ports:
        - containerPort: 8080