apiVersion: v1
kind: Service
metadata:
  name: login-msa-api-gateway-app-svc
spec:
  ports:
  - name: aplication-port
    port: 80
    targetPort: 8080
  selector:
    app: login-msa-api-gateway-app
  type: LoadBalancer
  loadBalancerIP: 192.168.29.22