apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/'
    targetRevision: 4.0.17
    chart: nfs-subdir-external-provisioner
    helm:
      valueFiles: []
      parameters:
        - name: nfs.server
          value: 192.168.29.14
        - name: nfs.path
          value: /nfsdir
        - name: storageClass.name
          value: nfs-storage
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
