apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simpleforum-kafka-sts
spec:
  serviceName: simpleforum-kafka-svc
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: simpleforum-kafka
        image: confluentinc/cp-kafka:7.0.9
        ports:
        - containerPort: 9092
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: simpleforum-zookeeper-sts-0.simpleforum-zookeeper-svc:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://$(MY_POD_NAME).simpleforum-kafka-svc:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        livenessProbe:
          exec:
            command: [ '/bin/bash', '-c', 'kafka-topics --bootstrap-server localhost:9092 --list' ]
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
          successThreshold: 1