apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: my-api-server
  newTag: "20230218061722"
- name: yellowsunn/my-api-server
  newTag: "20230218041904"
