apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleforum-kafka-ui-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: simpleforum-kafka-ui
        image: provectuslabs/kafka-ui
        ports:
        - containerPort: 8080