apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleforum-kafka-ui-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: simpleforum-kafka-ui
        image: provectuslabs/kafka-ui
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: local
        - name: KAFKA_CLUSTERS_0_ZOOKEEPER
          value: simpleforum-zookeeper-sts-0.simpleforum-zookeeper-svc:2181
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: simpleforum-kafka-sts-0.simpleforum-kafka-svc:9092, simpleforum-kafka-sts-1.simpleforum-kafka-svc:9092, simpleforum-kafka-sts-2.simpleforum-kafka-svc:9092