name: Change container image tag 
on:
  repository_dispatch:
    types: [change-image-tag]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Print Payload
        run: |
          echo ${{ github.event.client_payload.requested-event-path }}
          echo ${{ github.event.client_payload.container-image }}
          echo ${{ github.event.client_payload.deployment-version }}
          echo ${{ github.event.client_payload.overlay-path }}
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
      - name: Check kustomize version
        run: kustomize version
