apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simpleforum-mysql-board-sts
spec:
  replicas: 1
  serviceName: simpleforum-mysql-board-svc
  template:
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: simpleforum-mysql-board
        image: mysql:8.0.33
        ports:
        - protocol: TCP
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: board
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-uroot", "-ppassword", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1