apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-proxy-deploy
spec:
  revisionHistoryLimit: 5
  template:
    spec:
      containers:
      - name: imgproxy
        image: darthsim/imgproxy:v3.16
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 8080
        env:
        - name: IMGPROXY_S3_REGION
          value: 'ap-northeast-2'
        - name: IMGPROXY_USE_S3
          value: 'true'
        - name: IMGPROXY_ALLOW_ORIGIN
          value: '*'
        - name: IMGPROXY_FALLBACK_IMAGE_HTTP_CODE
          value: '400'
        - name: IMGPROXY_FALLBACK_IMAGE_DATA
          value: iVBORw0KGgoAAAANSUhEUgAAAQMAAADCCAMAAAB6zFdcAAAAOVBMVEXd3d3g4OCOjo7b29uoqKiRkZGioqKUlJS+vr7ExMSlpaW1tbXHx8exsbHU1NTMzMycnJzQ0NCtra0jU8DMAAADVUlEQVR4nO3YXXujKhSGYQEBERX0///YWQu0zbST2T3YnSS9nvsgjYHY8IbPDAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3GPMoz/B93Lu87MPyjr9ow/zECbP49aflpDvVFptvBfPT2BGa8f+bLHjnZamu+n8CGb00Rcd7n/JYPjJveDMoGob3zMw6vda7dJcJbcVzKeLawb9fJsnJWNhrX4yNxlseQ5z3m4q7dMij2XapzmM02DSEeap57VL5XCUXq+sQcr3KbWrZQxh3V8gBckgJx+3twzM5G0M0fr3pcBMNrjBHFZLvD2ytfJn1qLdykvVthCHybby2Ip0oqlSkp4/BM3ABLuaMwOTvF83tx2+zxKtzmRnKVm9Pza3RO9rcXtsrdtDcs5lq6NJXhr7OzWDycbUSra//fun0DIoNhbTM3DBjq3tc/+iW50rg6gXq7fSwU22RyvTUTTEWPSV6qTAVc1gq1b7htxuevqO0DIYDmlwz2DTOIY2MuJ+1Tkz0N7SBoa+lvqSaga3bVuVumbWO+mOQ29WfN10TpzOlfeZ9Qy2aJeWgTycndfFuJzf4FsGuWegHeDMwMg0WGP0mkG1bezLaJq1Vl1Fnn19VNO+rGfQ+vGVQZ/wpUunOxmsw1sGMoHWsOaoGcQzg6VnEGsXHtW0L+sZyPD1uWgG6W0Su98P3jPYog+bzAm194Ppth/M2+lRTfuyMwP58vz0cT64Pv3dDFpiOvO1sbDqCiqCZlB6yUs4M9BPXn1fF9Z2fdjwcW38UwahbSna/Fm8z7JMZN/Xhb5nGF4giCsDU2Td7/sDmzejq/zy3xnIoipbqSRzou4UZY8UVtkWaQYyw/jkjCvp+c8a14qmB2Rt6SDfo0xztTXuqtP3iWcG+WY+cKP1ofp4TocpxBjHuVWQjuXlPv4V9kgpL/2Zy7nt83W5CyGXm068Zw1kye1YUPob9lbbyQkirCVl3UvIdkBmwGtBcUnOC+F4gX5w8zPZdcqTbc/HX5TM7dB+Oxa2R617vjOlzbkSzqnxvM8LzAf/I9ke6/nJ1lc4K36XRc/R4yt0/u9jzMv8bAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPBP/QJjhBqSKPIs1AAAAABJRU5ErkJggg==
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef: 
              name: aws-iam-secret
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-iam-secret
              key: secret_access_key
      - name: imgproxy-nginx
        image: nginx:1.23.4-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          readOnly: true
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /js/image.js
          readOnly: true
          subPath: image.js
      volumes:
      - name: nginx-config
        configMap:
          defaultMode: 0644
          name: img-proxy-nginx-config
