apiVersion: v1
kind: Service
metadata:
  name: img-proxy-svc
spec:
  ports:
  - name: application-port
    port: 80
    targetPort: 80
  selector:
    app: imgproxy-nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.29.27
